### ISSUE TITLE
Needs nodes as dependency if jupyterlab support needed

### ISSUE THREAD

**Issue by JuanCab** [conda-forge/ipywebrtc-feedstock#18]
Issue: When attempting to follow the conda installation instructions in the docs for ipywebrtc, specifically:

```
$ conda install -c conda-forge ipywebrtc
$ jupyter labextension install jupyter-webrtc       # for jupyter lab
```
installation of the jupyterlab extension fails with
`ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.`

Can be fixed by installing `nodejs` via `conda install nodejs`.  As such, it strikes me that a dependency for `ipywebrtc` installations via conda-forge should be `nodejs`.
</details>

**Comment by maartenbreddels** [comment]
Hi,

Interesting point of view, but I don't think it should be ipywebrtc that depends on nodejs.

ipywebrtc depends on ipywidgets, if this idea is valid, ipywidgets should depend on nodejs (cc @jasongrout), or some future jupyter lab specific package that includes the jupyter-widgets bundle.

**Comment by jasongrout** [comment]
To push it further down the stack, this really has nothing to do with ipywidgets. It is installing extensions into JupyterLab that requires nodejs. And there we made the explicit decision to say that the base jupyterlab package should not require nodejs (for example, there is no way to require it in pip), but if you wanted to install extensions, you'd need to install nodejs separately.

That decision is at the level of the jupyterlab conda package. And perhaps the JLab conda package should depend on nodejs for convenience? But in any case, that discussion is an issue for this repo: https://github.com/conda-forge/jupyterlab-feedstock

**Comment by bollwyvl** [comment]
Probably can close this now :grin: ?

**Comment by marscher** [comment]
@JuanCab conda-forge/jupyterlab now install nodejs. Please close.

**Comment by maartenbreddels** [comment]
> Probably can close this now 😁 ?

yes :)
